name: objd_dungeon
description: A quick and easy dungeon generator for objd.
version: 0.1.2
author: Stevertus <stevertusyt@gmail.com>
homepage: https://stevertus.com/objD
repository: https://github.com/Stevertus/objd-dungeon
issue_tracker: https://github.com/Stevertus/objd-dungeon/issues
documentation: https://stevertus.com/objD/documentation/dungeon

environment:
  sdk: ">=2.0.0 <3.0.0"

dependencies:
  objd: latest
  meta: ^1.1.7

dev-dependencies:
  pedantic: latest