name: objd-dungeon
description: A quick and easy dungeon generator for objd.
 version: 0.1.0
author: Stevertus <stevertusyt@gmail.com>
homepage: https://stevertus.com/objD
repository: https://github.com/Stevertus/objD
issue_tracker: https://github.com/Stevertus/objD/issues
documentation: https://stevertus.com/objD/documentation

environment:
  sdk: '>=2.1.0 <3.0.0'

dependencies:
  objd:
    path: C:\webdev\Dart\objectiveD

